### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by NMelis** [kovetskiy/yota-cli#1]
Конфиг заполнен
```
melis@Melis:~$ go/bin/yota -B
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x498645]

goroutine 1 [running]:
panic(0x6682c0, 0xc420010110)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/kovetskiy/go-yota.(*Client).getUid(0xc420015f00, 0x0, 0x0, 0x0, 0x0)
	/home/melis/go/src/github.com/kovetskiy/go-yota/main.go:178 +0x1a5
github.com/kovetskiy/go-yota.(*Client).Login(0xc420015f00, 0x0, 0x0)
	/home/melis/go/src/github.com/kovetskiy/go-yota/main.go:71 +0x65d
main.main()
	/home/melis/go/src/github.com/kovetskiy/yota/main.go:61 +0x451

```

**Comment by kovetskiy** [comment]
The problem should be fixed in go-yota library: https://github.com/kovetskiy/go-yota/commit/dbb381b

Please rebuild and rerun.

**Comment by kovetskiy** [comment]
@ProgMeli is it fixed now?

**Comment by NMelis** [comment]
@kovetskiy, yes
